# .streamlit/secrets.toml

[tfb98903]
user          = "craghavendra"
password      = "qpb2ehf.mfp.FGH7xdj"
account       = "tfb98903.us-east-1"
warehouse     = "DEMO_WH"
role          = "ACCOUNTADMIN"
database      = "DEMO_DB"
schema	      = "PUBLIC"
