select distinct(WAREHOUSE_NAME)
from SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
where END_TIME >= dateadd(DAY, -30, current_date())
and warehouse_name not in ('CLOUD_SERVICES_ONLY')
GROUP by WAREHOUSE_NAME
ORDER BY WAREHOUSE_NAME 
;