select distinct(WAREHOUSE_NAME), SUM(CREDITS_USED) as CREDITS 
from SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
where END_TIME >= dateadd(DAY, -30, current_date())
GROUP by WAREHOUSE_NAME
ORDER BY credits DESC
;